runtime: nodejs10

env_variables:
  environment: "--prod"

api_version: 1
threadsafe: true
handlers:
- url: /
  secure: always
  static_files: dist/dev-profile/index.html
  upload: dist/dev-profile/index.html

skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE