runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: dist/dev-profile/index.html
  upload: dist/dev-profile/index.html
- url: /
  static_dir: dist/dev-profile
- url: /.*
  secure: always
  static_files: dist/dev-profile/index.html
  upload: dist/dev-profile/.*

skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE