steps:
  - name: node:18.19.0
    entrypoint: npm
    args: ["install --legacy-peer-deps"]
  - name: node:14.17.3
    entrypoint: npm
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"
